name: security

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    uses: atsushi-ambo/ci-workflows/.github/workflows/security.yml@e32497f0fb113b8a5556c218b4fef1ca398283c2
